config/routes.rb
Ipasa::Application.routes.draw do
  namespace :admin do
    root :to => 'base#index'
     match "propiedades" , :to => "properties#tab"
     resources :properties do
     end
  end

  root :to => "pages#home"
  match 'contacto', :to => "pages#contacto"
  match "nueva_factura", :to => "invoices#new"
  match "nueva_localidad",:to => "localities#new"
  match "subir_documento", :to => "documents#new"
  match "nuevo_inmueble", :to => "leases#new"
  match "nueva_foto", :to => "photos#new"
  match "nuevo_servicio", :to => "services#new"
  match "nueva_renta", :to => "rents#new"
  match "nueva_estructura", :to => "structures#new"
  match "nuevo_recargo", :to => "surcharges#new"
  match "nuevo_impuesto", :to => "duties#new"
  match "propiedades" , :to => "properties#tab"
  match "perfiles", :to => "profiles#tab"

  resources :profiles

  resources :types

  resources :rents

  resources :lease_structures       
  
  resources :rent_documents

  resources :invoices

  resources :surcharges

  resources :documents

  resources :structures

  resources :duties

  resources :property_services

  resources :services

  resources :videos

  resources :leases

  resources :localities

  resources :properties do
    member do
    get 'properties'

  end
end

end

app/models/locality.rb
class Locality < ActiveRecord::Base
  attr_accessible :nombre
  has_many :properties
end
# == Schema Information
#
# Table name: localities
#
#  id         :integer         not null, primary key
#  nombre     :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

app/controllers/localities_controller.rb
class LocalitiesController < ApplicationController
  # GET /localities
  # GET /localities.json
  def index
    @localities = Locality.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @localities }
    end
  end

  # GET /localities/1
  # GET /localities/1.json
  def show
    @locality = Locality.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @locality }
    end
  end

  # GET /localities/new
  # GET /localities/new.json
  def new
    @locality = Locality.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @locality }
    end
  end

  # GET /localities/1/edit
  def edit
    @locality = Locality.find(params[:id])
  end

  # POST /localities
  # POST /localities.json
  def create
    @locality = Locality.new(params[:locality])

    respond_to do |format|
      if @locality.save
        format.html { redirect_to @locality, notice: 'Locality was successfully created.' }
        format.json { render json: @locality, status: :created, location: @locality }
      else
        format.html { render action: "new" }
        format.json { render json: @locality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /localities/1
  # PUT /localities/1.json
  def update
    @locality = Locality.find(params[:id])

    respond_to do |format|
      if @locality.update_attributes(params[:locality])
        format.html { redirect_to @locality, notice: 'Locality was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @locality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /localities/1
  # DELETE /localities/1.json
  def destroy
    @locality = Locality.find(params[:id])
    @locality.destroy

    respond_to do |format|
      format.html { redirect_to localities_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/localities_helper.rb
module LocalitiesHelper
end

app/views/localities/_form.html.erb
<%= form_for @locality, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :nombre, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nombre, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                localities_path, :class => 'btn' %>
  </div>
<% end %>

app/views/localities/edit.html.erb
<%- model_class = @locality.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/localities/index.html.erb
<%- model_class = Locality.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @localities.each do |locality| %>
      <tr>
        <td><%= link_to locality.id, locality_path(locality) %></td>
        <td><%= locality.nombre %></td>
        <td><%=l locality.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_locality_path(locality), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      locality_path(locality),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_locality_path,
            :class => 'btn btn-primary' %>

app/views/localities/new.html.erb
<%- model_class = @locality.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/localities/show.html.erb
<%- model_class = @locality.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @locality.nombre %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              localities_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_locality_path(@locality), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              locality_path(@locality),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>