config/routes.rb
Ipasa::Application.routes.draw do
  namespace :admin do
    root :to => 'base#index'
     match "propiedades" , :to => "properties#tab"
     resources :properties do
     end
  end

  root :to => "pages#home"
  match 'contacto', :to => "pages#contacto"
  match "nueva_factura", :to => "invoices#new"
  match "nueva_localidad",:to => "localities#new"
  match "subir_documento", :to => "documents#new"
  match "nuevo_inmueble", :to => "leases#new"
  match "nueva_foto", :to => "photos#new"
  match "nuevo_servicio", :to => "services#new"
  match "nueva_renta", :to => "rents#new"
  match "nueva_estructura", :to => "structures#new"
  match "nuevo_recargo", :to => "surcharges#new"
  match "nuevo_impuesto", :to => "duties#new"
  match "propiedades" , :to => "properties#tab"
  match "perfiles", :to => "profiles#tab"

  resources :profiles

  resources :types

  resources :rents

  resources :lease_structures       
  
  resources :rent_documents

  resources :invoices

  resources :surcharges

  resources :documents

  resources :structures

  resources :duties

  resources :property_services

  resources :services

  resources :videos

  resources :leases

  resources :localities

  resources :properties do
    member do
    get 'properties'

  end
end

end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :property_id, :url , :descripcion
  belongs_to :property
end
# == Schema Information
#
# Table name: videos
#
#  id          :integer         not null, primary key
#  url         :string(255)
#  property_id :integer
#  descripcion :text
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @videos }
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/new
  # GET /videos/new.json
  def new
    @video = Video.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(params[:video])

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render json: @video, status: :created, location: @video }
      else
        format.html { render action: "new" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for @video, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :url, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :property_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :property_id, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                videos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<%- model_class = @video.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/videos/index.html.erb
<%- model_class = Video.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:url) %></th>
      <th><%= model_class.human_attribute_name(:property_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= link_to video.id, video_path(video) %></td>
        <td><%= video.url %></td>
        <td><%= video.property_id %></td>
        <td><%=l video.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_video_path(video), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      video_path(video),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_video_path,
            :class => 'btn btn-primary' %>

app/views/videos/new.html.erb
<%- model_class = @video.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/videos/show.html.erb
<%- model_class = @video.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:url) %>:</strong></dt>
  <dd><%= @video.url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:property_id) %>:</strong></dt>
  <dd><%= @video.property_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              videos_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_video_path(@video), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              video_path(@video),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>