config/routes.rb
Ipasa::Application.routes.draw do
  namespace :admin do
    root :to => 'base#index'
     match "propiedades" , :to => "properties#tab"
     resources :properties do
     end
  end

  root :to => "pages#home"
  match 'contacto', :to => "pages#contacto"
  match "nueva_factura", :to => "invoices#new"
  match "nueva_localidad",:to => "localities#new"
  match "subir_documento", :to => "documents#new"
  match "nuevo_inmueble", :to => "leases#new"
  match "nueva_foto", :to => "photos#new"
  match "nuevo_servicio", :to => "services#new"
  match "nueva_renta", :to => "rents#new"
  match "nueva_estructura", :to => "structures#new"
  match "nuevo_recargo", :to => "surcharges#new"
  match "nuevo_impuesto", :to => "duties#new"
  match "propiedades" , :to => "properties#tab"
  match "perfiles", :to => "profiles#tab"

  resources :profiles

  resources :types

  resources :rents

  resources :lease_structures       
  
  resources :rent_documents

  resources :invoices

  resources :surcharges

  resources :documents

  resources :structures

  resources :duties

  resources :property_services

  resources :services

  resources :videos

  resources :leases

  resources :localities

  resources :properties do
    member do
    get 'properties'

  end
end

end

app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :nombre
  has_many :rent_documents
  has_many :rents , through: :rent_documents
end
# == Schema Information
#
# Table name: documents
#
#  id         :integer         not null, primary key
#  nombre     :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @documents }
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @document = Document.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.json
  def new
    @document = Document.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(params[:document])

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render json: @document, status: :created, location: @document }
      else
        format.html { render action: "new" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.json
  def update
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for @document, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :nombre, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nombre, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                documents_path, :class => 'btn' %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/documents/index.html.erb
<%- model_class = Document.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= link_to document.id, document_path(document) %></td>
        <td><%= document.nombre %></td>
        <td><%=l document.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_document_path(document), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      document_path(document),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_document_path,
            :class => 'btn btn-primary' %>

app/views/documents/new.html.erb
<%- model_class = @document.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/documents/show.html.erb
<%- model_class = @document.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @document.nombre %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              documents_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_document_path(@document), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              document_path(@document),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>