config/routes.rb
Ipasa::Application.routes.draw do
  namespace :admin do
    root :to => 'base#index'
     match "propiedades" , :to => "properties#tab"
     resources :properties do
     end
  end

  root :to => "pages#home"
  match 'contacto', :to => "pages#contacto"
  match "nueva_factura", :to => "invoices#new"
  match "nueva_localidad",:to => "localities#new"
  match "subir_documento", :to => "documents#new"
  match "nuevo_inmueble", :to => "leases#new"
  match "nueva_foto", :to => "photos#new"
  match "nuevo_servicio", :to => "services#new"
  match "nueva_renta", :to => "rents#new"
  match "nueva_estructura", :to => "structures#new"
  match "nuevo_recargo", :to => "surcharges#new"
  match "nuevo_impuesto", :to => "duties#new"
  match "propiedades" , :to => "properties#tab"
  match "perfiles", :to => "profiles#tab"

  resources :profiles

  resources :types

  resources :rents

  resources :lease_structures       
  
  resources :rent_documents

  resources :invoices

  resources :surcharges

  resources :documents

  resources :structures

  resources :duties

  resources :property_services

  resources :services

  resources :videos

  resources :leases

  resources :localities

  resources :properties do
    member do
    get 'properties'

  end
end

end

app/models/property.rb
class Property < ActiveRecord::Base	
  attr_accessible :descripcion, :direccion, :google, :locality_id, :nombre, :num_ext, :ofertada , :user_id , :catastro , :pictures_attributes 
  belongs_to :locality
  belongs_to :user
  has_many :duties
  has_many :videos
  has_many :photos
  has_many :property_services
  has_many :services , through: :property_services   
  has_many :leases
  has_many :profiles
  ##===Atributos especificos para el uso de paperclip
  has_many :pictures , :dependent => :destroy
  accepts_nested_attributes_for :pictures , 
  :reject_if => lambda { |a| a[:picture_descripcion].blank? } , 
  :allow_destroy => true 
end
# == Schema Information
#
# Table name: properties
#
#  id          :integer         not null, primary key
#  locality_id :integer
#  user_id     :integer
#  nombre      :string(255)
#  propietario :string(255)
#  num_ext     :integer
#  direccion   :text
#  google      :string(255)
#  descripcion :text
#  ofertada    :boolean
#  catastro    :string(255)
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#  clave       :string(255)
#

app/controllers/admin/properties_controller.rb
class 	Admin::PropertiesController < Admin::ResourceController
  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @properties }
      format.js
    end
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @property = Property.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @property }
      format.js
    end
  end

  # GET /properties/new
  # GET /properties/new.json
  def new
    @property = Property.new
    6.times { @property.pictures.build }

    @localities = Locality.all
    respond_to do |format|
      format.html  # new.html.erb
      format.json { render json: @property }
      format.js
    end
  end

  # GET /properties/1/edit
  def edit
    @property = Property.find(params[:id])
    6.times { @property.pictures.build }
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(params[:property])

    respond_to do |format|
      if @property.save
        format.html { redirect_to action:"tab", notice: 'Property was successfully created.' }
        format.json { render json: @property, status: :created, location: @property }
      else
        format.html { render action: "new" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /properties/1
  # PUT /properties/1.json
  def update
    @property = Property.find(params[:id])
    respond_to do |format|
      if @property.update_attributes(params[:property])
        format.html { redirect_to action: "tab" }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property = Property.find(params[:id])
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url }
      format.json { head :no_content }
    end
  end
  def tab
    @properties = Property.all
     respond_to do |format|
      format.html
    end
  end



end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController


  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @properties }
      format.js
    end
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @property = Property.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @property }
      format.js
    end
  end

  # GET /properties/new
  # GET /properties/new.json
  def new
    @property = Property.new
    6.times { @property.pictures.build }

    @localities = Locality.all
    respond_to do |format|
      format.html  # new.html.erb
      format.json { render json: @property }
      format.js
    end
  end

  # GET /properties/1/edit
  def edit
    @property = Property.find(params[:id])
    6.times { @property.pictures.build }
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(params[:property])

    respond_to do |format|
      if @property.save
        format.html { redirect_to action:"tab", notice: 'Property was successfully created.' }
        format.json { render json: @property, status: :created, location: @property }
      else
        format.html { render action: "new" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /properties/1
  # PUT /properties/1.json
  def update
    @property = Property.find(params[:id])
    respond_to do |format|
      if @property.update_attributes(params[:property])
        format.html { redirect_to action: "tab" }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property = Property.find(params[:id])
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url }
      format.json { head :no_content }
    end
  end
  def tab
    @properties = Property.all
     respond_to do |format|
      format.html
    end
  end



end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/admin/properties/_form.html.erb
<%= form_for @property, :html => { :class => 'form-horizontal', :multipart => true } do |f| %>
  <div class="control-group">
    <%= f.label :nombre, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nombre, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :num_ext, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :num_ext, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :direccion, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :direccion, :class => 'text_area', :cols  => '300', :rows => '10' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :google, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :google, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :descripcion, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :descripcion, :class => 'text_area', :cols  => '300', :rows => '10' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :ofertada, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :ofertada, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :locality_id, :class => 'control-label' %>
    <div class="controls">
     <%= select("property", "locality_id", Locality.all.collect {|l| [ l.nombre, l.id ] }, {:prompt => 'Seleccione una Localidad'}) %>
    </div>
  </div>

  <%= f.fields_for :pictures do |picture_fields| %>
  <% if picture_fields.object.new_record? %>
      <div>
       <%= picture_fields.file_field :picture %>
       <div class="control-group">
    <%= picture_fields.label "Descripcion de la imagen", :class => 'control-label' %>
    <div class="controls">
      <%= picture_fields.text_field :picture_descripcion, :class => 'text_field' %>
    </div>
      </div>
    <%end%>

  <%end%>

  <div class="well">
  <h2>Eliminar y Editar Imagenes</h2>
  <%= f.fields_for :pictures do |picture_fields| %>
  <% unless picture_fields.object.new_record? %>
       <%= link_to image_tag(picture_fields.object.picture.url(:thumb)) , picture_fields.object.picture.url(:original) %>
       
       <%= picture_fields.check_box :_destroy %>
      <div class="control-group">
      <%= picture_fields.label "Descripcion de la imagen", :class => 'control-label' %>
      <div class="controls">
      <%= picture_fields.text_field :picture_descripcion, :class => 'text_field' %>
    </div>
  </div>
    <%end%>
  </div>
  <%end%>
  </div>
  <div class="form-actions">
    <%= f.submit "Subir Propiedad", :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/properties/edit.html.erb
<%- model_class = @property.class -%>

<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/properties/edit.js.erb
$(document).ready(function() {
$('.modal-body').html("<%= escape_javascript render(:file => 'properties/edit', :formats => [:html])  %>");    
});

app/views/admin/properties/index.html.erb
<%- model_class = Property.new.class -%>  
  <div class="page-header">
  <h1>Listado de Propiedades</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:num_ext) %></th>
      <th><%= model_class.human_attribute_name(:direccion) %></th>
      <th><%= model_class.human_attribute_name(:ofertada) %></th>
      <th>Localidad</th>
      <th>Opciones</th>
    </tr>
  </thead>
  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%=  link_to property.nombre, property_path(property) %></td>
        <td><%= property.num_ext %></td>
        <td><%= property.direccion %></td>
        <td><% if property.ofertada == true %>
          <i class="icon-ok"></i>
          <% else %>
          <i class="icon-remove"></i>
          <% end %>
        </td>
        <td><%= property.locality.nombre %></td>
        <td>
          <%= link_to 'Mostrar', property_path(property), {:remote => true , 'data-toggle' =>  "modal", 'data-target' => "#modal-window", 'data-keyboard' => true , 'data-backdrop' => true , :class => "btn btn-mini btn-success"} %>
          <%= link_to 'Editar', edit_property_path(property) , {:remote => true , 'data-toggle' =>  "modal", 'data-target' => "#modal-window", 'data-keyboard' => true , 'data-backdrop' => true , :class => "btn btn-mini btn-primary"}  %>
          <%= link_to 'Eliminar', property_path(property), :method => :delete,:confirm => '¿Estas Seguro?', :class => 'btn btn-mini btn-danger' %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/admin/properties/index.js.erb
$(document).ready(function() {
    $('#content').html("<%= escape_javascript render(:file => 'properties/index', :formats => [:html])  %>");
});

app/views/admin/properties/new.html.erb
<div>
<h1>Nueva Propiedad</h1>
<%= render :partial => 'form' %>
</div>

app/views/admin/properties/new.js.erb
$(document).ready(function() {
    $('#content').html("<%= escape_javascript render(:file => 'properties/new', :formats => [:html])  %>");
});

app/views/admin/properties/show.html.erb
<div class="page-header">
  <h1><%= @property.nombre %></h1>
</div>
<div class= "well">
  <strong>Nombre :</strong>
  <%= @property.nombre %></br>
  <strong>Numero Exterior :</strong>
  <%= @property.num_ext %></br>
  <strong>Direccion :</strong>
  <%= @property.direccion %></br>
  <strong>Direccion Gooogle :</strong>
  <%= @property.google %></br>
  <strong>Descripcion :</strong>
  <%= @property.descripcion %></br>
  <strong>¿En oferta? :</strong>
  <% if @property.ofertada == true %>
          Si
          <% else %>
          No
          <% end %>
  </br><strong>Localidad :</strong>
  <%= @property.locality.nombre %>
</div>
<div class="well">
  <h1> Imagenes Asociadas a la Propiedad</h1>
 <% @property.pictures.each do |image| %>
 <%= link_to image_tag(image.picture.url(:thumb)) , image.picture.url(:original) %>
<% end %>
</div>

app/views/admin/properties/show.js.erb
$(document).ready(function() {
$('.modal-body').html("<%= escape_javascript render(:file => 'properties/show', :formats => [:html])  %>");    
});

app/views/admin/properties/tab.html.erb
<ul class="nav nav-tabs">
  <li class="active"><%= link_to "Lista", properties_path(:format => :js) , :remote => true , 'data-toggle' => 'tab' %></li>
  <li><%= link_to "Nueva  Propiedad", {:controller => "properties", :action => "new" , :format => :js}, :remote => true , 'data-toggle' => 'tab'%></li>
</ul>
 <div id="content" class="tab-pane active"> 
 	
<%= render(:file => 'properties/index') %>
</div>
 